services:
  postgresql-db:
    container_name: charly-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - /root/charly:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=charly
    command: ["postgres", "-c", "log_statement=all"]

  poller:
    container_name: charly-poller
    build:
      context: ./poller
      dockerfile: Dockerfile
    links:
      - postgresql-db

  api:
    container_name: charly-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
        - 5000:5000
    links:
      - postgresql-db

  