services:
  postgresql-db:
    container_name: charly-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - /charly:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=charly
    command: ["postgres", "-c", "log_statement=all"]

  poller:
    container_name: charly-poller
    build:
      context: ./poller
      dockerfile: Dockerfile
    links:
      - postgresql-db

  api:
    container_name: charly-app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
        - 42069:42069
    links:
      - postgresql-db

  discord:
    container_name: charly-discord
    build:
      context: ./discord
      dockerfile: Dockerfile
    links:
      - api