name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker-compose build

      - name: Start Database
        run: docker-composte up -d postgresql-db
        
      - name: Start API
        run: docker-composte up -d api
      
      - name: Start Poller
        run: docker-composte up -d poller
        
      - name: Start Discord
        run: docker-composte up -d discord
